# Generated by Django 4.0.4 on 2022-05-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tipo', models.IntegerField()),
            ],
        ),
    ]
