# Generated by Django 4.0.4 on 2022-05-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='categoria',
            field=models.CharField(default='Nova Categoria', max_length=100),
        ),
    ]
